= Exercise 2: Solutions to Written Problems
:stem: latex
:source-highlighter: rouge
:imagesdir: ./media

//:base-dir: ..
//ifdef::env-ilias[]
:base-dir: https://github.tik.uni-stuttgart.de/inm-RAMlab/LectureCDR/blob/master
//endif::[]

:scripts: link:{base-dir}/scripts
:lib: link:{base-dir}/lib
:unit_tests: link:{base-dir}/unit_tests

Many of these solutions are from previous iterations of the course. They have
been updated to reflect this year’s iteration of the problem set.  *For coding
problems, see source code in the GitHub repository for solutions.*

== Problem 2.2 Understanding Rotation Matrices

The quick and easy test is to verify that the matrix is an element of
stem:[SO(3)], which boils down to showing that for a stem:[3 \times 3] matrix
stem:[R], stem:[R^TR = I] and stem:[\det(R) = +1].  We further break down the
errors with the matrices in this problem.

. Matrix *(d)* has an element of 1.354. The associated column/row is hence longer
than 1, and the matrix therefore cannot be orthonormal.

. For this part of the problem, let's examine the matrices in turn.
.. Matrices *(a)* and *(d)* are symmetric. Since, the inverse is equal to the
transpose, these matrices would have to be their own inverse.  This is
obviously not true (it only holds for the identity) and, hence, they are not
elements in stem:[SO(3)].
.. Matrices *(b)* and *(c)* are equal apart from the signs in the second
column. One of these must hence be a left-handed coordinate system.  One could
check this by visualizing the basis vectors, or realize that for matrix *(c)*,
each term in the determinant formula is negative which leads to a negative
determinant of the matrix; hence, the matrix cannot represent a rotation. Thus,
matrix *(b)* remains as the correct answer.

. See the example on p. 70 in
http://hades.mech.northwestern.edu/images/2/25/MR-v2.pdf#page=90[Modern
Robotics] for the solution.

. We want to premultiply our matrices because we want the rotations to occur in
fixed-frame coordinates.  This leads to stem:[R = Rot(\hat{z}, \gamma)
Rot(\hat{y}, \beta) Rot(\hat{x}, \alpha)].  We would then apply the rotation to
a frame \{b\} relative to \{s\} as stem:[RR_{sb}].


== Problem 2.7: Integrating Angular Velocities, Part III: Integration with stem:[\hat{\omega}]

. The method in Problem 2.5 integrates stem:[\dot{R}_{sc}(t)] to obtain the
transformation matrix stem:[R_{sc}(t)] and numerical errors are introduced
directly to this matrix. Because of that, stem:[R_{sc}(t)] ceases to be an orthonormal
matrix that represents rotation. You can see that, for example, in the last
frame of the animation where the coordinate vectors have changed in length. In
contrast, Problem 2.6 integrates the Cardan angles which at any point in time
define a valid rotation matrix. So, even though the angle values accumulate
integration errors, the resulting transformation stem:[R_{sc}(t)] based on
these angles is always in stem:[SO(3)]. This makes the method in Problem 2.6
more suited to describe angular motions.

. See {scripts}/integrate_omega_hat.m[integrate_omega_hat.m].  We modified the
animation for loop in {scripts}/integrate_rdot.m[integrate_rdot.m] from
+
```matlab
for i = 1:n
    % Compute derivative using one of the equations above
    R_dot_sc = omega_s_mat * R_sc;
    
    % computer the Euler step
    R_sc = R_sc + R_dot_sc  * delta_t;
    c.R = R_sc;
    drawnow();
    
    % add the frame so we can create an animation later
    snapshots = Utils.takesnapshot(env, snapshots);
end
```
+
to
+
```matlab
for i = 1:n
    % Compute derivative using one of the equations above
    % R_dot_sc = omega_s_mat * R_sc; <- don't need this anymore!
    
    % computer the Euler step
    R_sc = (eye(3) + sin(delta_t) * omega_s_mat ...
        + (1 - cos(delta_t)) * omega_s_mat^2) * R_sc;
    c.R = R_sc;
    drawnow();
    
    % add the frame so we can create an animation later
    snapshots = Utils.takesnapshot(env, snapshots);
end
```

NOTE: Technically we added two lines in the editor, but with the line
continuation Matlab treats it as one long line.  We'll use this more liberal
definition for this problem.