= Computational Dynamics for Robotics
:toc:
:toc-placement!:
:repo: link:https://github.tik.uni-stuttgart.de/inm-RAMlab/LectureCDR/tree

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

The code in this repository accompanies the lecture **Computational Dynamics for Robotics** held at the University of Stuttgart.

IMPORTANT: The code will be updated as we go along the semester. 

toc::[]

== FAQ

How do I checkout the templates (code with no solutions) for a particular Exercise?::
For Exercise _N_, you would checkout `vN.0-templates`.  For example, to get the templates for Exercise 2, type
```matlab
!git checkout v2.0-templates
```

How do I checkout the solution for a particular Exercise?::
For Exercise _N_, you would checkout `vN.0`.  For example, to get the solutions for Exercise 1, type
```matlab
!git checkout v1.0
```


== Branches
Here we list a summary of branches and tags in the repository.

master:: The main branch, where the current templates and solutions are kept.  We also maintain the official version of the library here.
Ex1:: Ex1 contains solutions to Exercise 1 ({repo}/v1.0[v1.0]).
Ex2:: Ex2 contains templates and solutions to Exercise 2 ({repo}/v2.0-templates[v2.0-templates], {repo}/v2.0[v2.0]).
sandbox:: deprecated; this branch has been deleted from the repo.

== Contributing

Feel free to raise issues. If you would like to make a code contribution, feel free to fork the repository and make a pull request. Otherwise, you can directly clone this repository and you can play around with the code. We strongly recommend learning the basics of git.
