function out1 = GravitationalForces(in1,in2)
%GRAVITATIONALFORCES
%    OUT1 = GRAVITATIONALFORCES(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Jan-2021 21:52:22

% ✨ Automatically generated using EulerLagrange.m. ✨
L1 = in2(:,4);
L2 = in2(:,5);
g = in2(:,6);
m1 = in2(:,7);
m2 = in2(:,8);
m3 = in2(:,9);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
r1 = in2(:,10);
r2 = in2(:,11);
r3 = in2(:,12);
t2 = cos(q1);
t3 = q1+q2;
t4 = L1.*t2;
t5 = cos(t3);
t6 = q3+t3;
t7 = cos(t6);
t8 = L2.*t5;
t9 = r3.*t7;
out1 = [g.*m2.*(t4+r2.*t5)+g.*m3.*(t4+t8+t9)+g.*m1.*r1.*t2;g.*m3.*(t8+t9)+g.*m2.*r2.*t5;g.*m3.*t9];
