function out1 = KE(in1,in2,in3)
%KE
%    OUT1 = KE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Jan-2021 21:52:23

% ✨ Automatically generated using EulerLagrange.m. ✨
I1zz = in3(:,1);
I2zz = in3(:,2);
I3zz = in3(:,3);
L1 = in3(:,4);
L2 = in3(:,5);
m1 = in3(:,7);
m2 = in3(:,8);
m3 = in3(:,9);
q2 = in1(2,:);
q3 = in1(3,:);
q1dot = in2(1,:);
q2dot = in2(2,:);
q3dot = in2(3,:);
r1 = in3(:,10);
r2 = in3(:,11);
r3 = in3(:,12);
t2 = cos(q2);
t3 = cos(q3);
t4 = q2+q3;
t5 = L1.^2;
t6 = L2.^2;
t7 = q1dot.^2;
t8 = q2dot.^2;
t9 = q3dot.^2;
t10 = r2.^2;
t11 = r3.^2;
t12 = cos(t4);
out1 = (I1zz.*t7)./2.0+(I2zz.*t7)./2.0+(I2zz.*t8)./2.0+(I3zz.*t7)./2.0+(I3zz.*t8)./2.0+(I3zz.*t9)./2.0+(m1.*r1.^2.*t7)./2.0+I2zz.*q1dot.*q2dot+I3zz.*q1dot.*q2dot+I3zz.*q1dot.*q3dot+I3zz.*q2dot.*q3dot+(m2.*t5.*t7)./2.0+(m3.*t5.*t7)./2.0+(m3.*t6.*t7)./2.0+(m3.*t6.*t8)./2.0+(m2.*t7.*t10)./2.0+(m2.*t8.*t10)./2.0+(m3.*t7.*t11)./2.0+(m3.*t8.*t11)./2.0+(m3.*t9.*t11)./2.0+m3.*q1dot.*q2dot.*t6+m2.*q1dot.*q2dot.*t10+m3.*q1dot.*q2dot.*t11+m3.*q1dot.*q3dot.*t11+m3.*q2dot.*q3dot.*t11+L1.*L2.*m3.*t2.*t7+L1.*m2.*r2.*t2.*t7+L2.*m3.*r3.*t3.*t7+L2.*m3.*r3.*t3.*t8+L1.*m3.*r3.*t7.*t12+L1.*L2.*m3.*q1dot.*q2dot.*t2+L1.*m2.*q1dot.*q2dot.*r2.*t2+L2.*m3.*q1dot.*q2dot.*r3.*t3.*2.0+L2.*m3.*q1dot.*q3dot.*r3.*t3+L2.*m3.*q2dot.*q3dot.*r3.*t3+L1.*m3.*q1dot.*q2dot.*r3.*t12+L1.*m3.*q1dot.*q3dot.*r3.*t12;
