function out1 = PE(in1,in2)
%PE
%    OUT1 = PE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-Jan-2021 03:33:23

% ✨ Automatically generated using EulerLagrange.m. ✨
L1 = in2(:,4);
L2 = in2(:,5);
g = in2(:,6);
m1 = in2(:,7);
m2 = in2(:,8);
m3 = in2(:,9);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
r1 = in2(:,10);
r2 = in2(:,11);
r3 = in2(:,12);
t2 = sin(q1);
t3 = q1+q2;
t4 = sin(t3);
out1 = g.*(L1.*m2.*t2+L1.*m3.*t2+L2.*m3.*t4+m1.*r1.*t2+m2.*r2.*t4+m3.*r3.*sin(q3+t3));
